### ISSUE TITLE
Typeface in header not appearing correctly

### ISSUE THREAD

**Issue by helenvholmes** [FirefoxUX/SharedBanner#2]
<img width="1280" alt="screen shot 2015-12-18 at 2 13 29 pm" src="https://cloud.githubusercontent.com/assets/1720093/11904963/8f2d34b4-a591-11e5-8d0f-fc91ed3831e7.png">

:sob: 

As per discussion in #ux, I think it would be helpful to add the typeface `@font-face` instructions to the README.

**Comment by darrinhenein** [comment]
And at the *very* least, some sensible fallbacks :)

**Comment by aminalhazwani** [comment]
We can close this one ☺️
