### ISSUE TITLE
Post the files to a CDN, and push them there on new commits/PRs.

### ISSUE THREAD

**Issue by bwinton** [FirefoxUX/SharedBanner#7]
I think Mozilla has a CDN, and I also think we want to use Travis…

**Comment by strugee** [comment]
Note also that rawgithub.com discourages hotlinking to it in the manner suggested by the README.

**Comment by bwinton** [comment]
(I'm fairly clearly not working on this…  😉)

**Comment by strugee** [comment]
@bwinton looks like `fxux-banner.js` (as well as the minified variant) are published on GitHub Pages - didn't notice that before. I think that means that the only thing left to do is fix the README, right?

Will send patches shortly.
